main: me.Plugins.SimpleFactions.SimpleFactions
api-version: 1.20
name: SimpleFactions
version: 1.0
author: Drefvelin

depend: [DenarEconomy]
softdepend: [MMOItems, MythicLib, DenarEconomy]

commands:
  faction:
      useage: /<command>
      description: Faction Command