main: me.Plugins.SimpleFactions.SimpleFactions
api-version: 1.20
name: SimpleFactions
version: 1.0
author: Drefvelin

depend: [DenarEconomy, TLibs]
softdepend: [MMOItems, MythicLib, TFMCWeb, VehicleFramework, VFBuilders]

commands:
  faction:
      useage: /<command>
      description: Faction Command
  guild:
      useage: /<command>
      description: Guild Command
  warband:
      useage: /<command>
      description: Warband Command
  battle:
      useage: /<command>
      description: Battle Command
  ledger:
      useage: /<command>
      description: View your daily cashflow ledger