package me.Plugins.SimpleFactions.enums;

public enum SFGUI {
	MILITARY_VIEW,
	DIPLOMACY_VIEW,
	ATTITUDE_VIEW,
	RELATION_VIEW,
	FACTION_VIEW,
	TIER_VIEW,
	TITLE_VIEW,
	TITLE_TYPE_VIEW,
	WAR_LIST,
	WAR_VIEW,
	PARTICIPANT_VIEW,
	WARGOAL_VIEW,
}
